### ISSUE TITLE
deprecation warnings for Gns-1 on Wesnoth 1.15.x

### ISSUE THREAD

**Issue by knyghtmare** [nemaara/Genesis#3]
[wesnoth-20210420-015956-20024.log](https://github.com/nemaara/Genesis/files/6339155/wesnoth-20210420-015956-20024.log)

Every turn has like 5-6 warnings being thrown at turn start. 

I am starting S3 now.

**Comment by nemaara** [comment]
Forgot to close when porting, reopen if not fixed.
